### ISSUE TITLE
[BUG] val does not infer generic types in Java 14 switch expressions

### ISSUE THREAD

**Issue by borisfox73** [projectlombok/lombok#2624]
**Describe the bug**
val fails to correctly infer generic type when used inside the switch expression block. It infers Object instead.

**To Reproduce**
```
import lombok.val;

import java.util.Map;

public class TestSwitchVal2 {

	public void test(int arg) {
		val x = switch (arg) {
			default -> {
				val map = Map.of("test", 1);
				yield map;
			}
		};
	}
}
```
C:\Users\boris\IdeaProjects\TestLombokJava14\src>javac -cp ..\lib\lombok-1.18.16.jar TestSwitchVal2.java
TestSwitchVal2.java:16: error: incompatible types: bad type in switch expression
                                yield map;
                                      ^
    Object cannot be converted to val
1 error

**Expected behavior**
map variable is expected to be inferred of correct type (Map<String,Integer).

**Version info (please complete the following information):**
 - Lombok version: 1.18.16
 - Platform: javac 14.0.2

**Comment by Rawi01** [comment]
This was fixed in #2792 and is already part of the latest 1.18.20 release.

**Comment by borisfox73** [comment]
Following code
```
public class TestSwitchVal1 {

	public void test(int arg) {
		val map = Map.of("test1", 1);
		val x = switch (arg) {
			default -> {
				val c = new HashMap<>(map);
				f(c);
				yield arg;
			}
		};
	}

	public void f(Map<String, Integer> m) {
	}
}
```
still does not compile with latest JDK 14 and 15.

```
TestSwitchVal1.java:21: error: method f in class TestSwitchVal1 cannot be applied to given types;
                                f(c);
                                ^
  required: Map<String,Integer>
  found:    Object
  reason: argument mismatch; Object cannot be converted to Map<String,Integer>
1 error
```

It does with JDK 16, though.

**Comment by Rawi01** [comment]
That is a problem in the java compiler that was [fixed](https://github.com/openjdk/jdk/commit/b37228e11fc69128b8172968e6b1049bcb9cb994) in Java 16. I think we can handle that in lombok.
