### ISSUE TITLE
[BUG] Eclipse installation certificate expired

### ISSUE THREAD

**Issue by dstango** [projectlombok/lombok#3311]
I started installing the newest version of eclipse, and was installing importing lombok from an old Eclipse installation (File -> Import -> From existing installation).

Eclipse takes it as an opportunity to fetch the most current version from the update site.

It shows a warning that the certificate is expired - the details look like this:
![image](https://user-images.githubusercontent.com/13139522/206570869-66b1be2a-a648-4024-84d4-b6b15ce5882b.png)

**Version info (please complete the following information):**
 - Lombok version 1.18.24
 - Platform: eclipse 2022-12

**Comment by chovyy** [comment]
I think, this is a quite critical issue and should be fixed as soon as possible.

**Comment by TheHaf** [comment]
This is still an issue for the newest version 1.18.26.

And I agree that this is a quite critical issue.

**Comment by wayoubi** [comment]
Facing the same problem

![Screenshot 2023-03-26 at 12 58 16 PM](https://user-images.githubusercontent.com/14363692/227791828-135dda4a-b5ca-42d9-a2a5-76cda8a31ab4.png)
![Screenshot 2023-03-26 at 12 59 41 PM](https://user-images.githubusercontent.com/14363692/227791855-83c1f1fe-22ef-496d-a888-ec5e59302007.png)

**Comment by danthe1st** [comment]
From [the docs](https://projectlombok.org/setup/eclipse):
> WARNING: This plugin installer is currently unsigned, and we have given up on figuring out how to fix that; if team eclipse or somebody else can help us out, we're all ears!
So I guess that's the reason.

**Comment by kwin** [comment]
The Eclipse bundles are not(!) unsigned, they have a X509 signature which expired. Probably switching to the also supported PGP signature (https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fp2_pgp.html) which doesn't require a CA is reasonable for Lombok.
The affected Jars are: org.projectlombox.agent, 1.18.32 and org.projectlombox.feature 1.18.32.

**Comment by rzwitserloot** [comment]
The last time we looked at this, the situation was incredibly stupidly set up by eclipse. Or, more likely, we just didn't understand it.

This would be an absolutely excellent time for all you 'I think this is critical!!' non-contributing complainers to do something useful and tell us how to do a better job. Self signed certificates are completely useless. In fact, they are as useless as an expired self signed cert, really.

The fix is to have it properly signed, but, the last time Roel and I spent 3 days trying to figure out how to do that and we did not manage to do it.

My rate for doing a week's worth of work I really hate to do is very high.

Fortunately, as per [this doc](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fp2_pgp.html) as linked by @kwin it looks like eclipse has improved certain matters, though I still fail to see how this helps much, given that there's no real way to verify this sigs.

Roel and I might try again if we feel like it. A step by step guide and more insights as to how a user of eclipse is meant to interact with the signature would be swell. For example, for https, the interaction is: "Well my browser / OS ships with something like 8 hardcoded known root CAs and we check if the signature provided by a website we visit via https has a chain of signatures that are all valid and end in one of those hardcoded CAs and it yells quite loudly if this check fails" - an interaction that has so far worked rather well. For the original PGP it was "well you are meant to get together in person at key sharing parties and share keys in person there, then there's this web of trust thing." which didn't work as well but as a 'model of interaction' it was rather clear.

These eclipse signatures I don't really get. They're all self signed aren't they? Users aren't going to check any of these so what's the point?

It feels like we are forced to jump to badly documented hoops to produce pointless security drivel which is not fun. I'm sure I'm misunderstanding something, but an explanation would be swell. We know how PKI works.

**Comment by kingthorin** [comment]
@rzwitserloot thanks very much for the detailed response!
I agree from your write-up it does seem like a security theatre "control". I'll try to do some reading/research and see if I can find anything more convincing.
